//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContactsTracker.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 If you have a suggestion for a new query, please let me know. 的本地化字符串。
        /// </summary>
        internal static string AnalyzeFeedback {
            get {
                return ResourceManager.GetString("AnalyzeFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discord: @lamitt 的本地化字符串。
        /// </summary>
        internal static string AuthorDiscord {
            get {
                return ResourceManager.GetString("AuthorDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Delete at Data Tab 的本地化字符串。
        /// </summary>
        internal static string ButtonDeleteAll {
            get {
                return ResourceManager.GetString("ButtonDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete ALL Active Entries 的本地化字符串。
        /// </summary>
        internal static string ButtonDeleteAllAction {
            get {
                return ResourceManager.GetString("ButtonDeleteAllAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show the button to delete all active entries at Data Tab. 的本地化字符串。
        /// </summary>
        internal static string ButtonDeleteAllTooltip {
            get {
                return ResourceManager.GetString("ButtonDeleteAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete ALL? This action is irreversible. 的本地化字符串。
        /// </summary>
        internal static string ButtonDeleteAllWarning {
            get {
                return ResourceManager.GetString("ButtonDeleteAllWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        internal static string ButtonQuery {
            get {
                return ResourceManager.GetString("ButtonQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string ButtonSelectNo {
            get {
                return ResourceManager.GetString("ButtonSelectNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string ButtonSelectYes {
            get {
                return ResourceManager.GetString("ButtonSelectYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CancelIgnore {
            get {
                return ResourceManager.GetString("CancelIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep Incomplete Entry 的本地化字符串。
        /// </summary>
        internal static string CheckboxEnableKeepEntry {
            get {
                return ResourceManager.GetString("CheckboxEnableKeepEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep record regardless of completion. 的本地化字符串。
        /// </summary>
        internal static string CheckboxEnableKeepEntryTooltip {
            get {
                return ResourceManager.GetString("CheckboxEnableKeepEntryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Logging 的本地化字符串。
        /// </summary>
        internal static string CheckboxEnableLogging {
            get {
                return ResourceManager.GetString("CheckboxEnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable to start recording data. 的本地化字符串。
        /// </summary>
        internal static string CheckboxEnableLoggingTooltip {
            get {
                return ResourceManager.GetString("CheckboxEnableLoggingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Log Party 的本地化字符串。
        /// </summary>
        internal static string CheckboxEnableLogParty {
            get {
                return ResourceManager.GetString("CheckboxEnableLogParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Party Class 的本地化字符串。
        /// </summary>
        internal static string CheckboxEnableLogPartyClass {
            get {
                return ResourceManager.GetString("CheckboxEnableLogPartyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Also record their class. 的本地化字符串。
        /// </summary>
        internal static string CheckboxEnableLogPartyClassTooltip {
            get {
                return ResourceManager.GetString("CheckboxEnableLogPartyClassTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable to log party members on completion. 的本地化字符串。
        /// </summary>
        internal static string CheckboxEnableLogPartyTooltip {
            get {
                return ResourceManager.GetString("CheckboxEnableLogPartyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only Record Duty Roulette 的本地化字符串。
        /// </summary>
        internal static string CheckboxEnableRecordRoulette {
            get {
                return ResourceManager.GetString("CheckboxEnableRecordRoulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable to only record duty joined by roulette. 的本地化字符串。
        /// </summary>
        internal static string CheckboxEnableRecordRouletteTooltip {
            get {
                return ResourceManager.GetString("CheckboxEnableRecordRouletteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record Solo 的本地化字符串。
        /// </summary>
        internal static string CheckboxEnableRecordSolo {
            get {
                return ResourceManager.GetString("CheckboxEnableRecordSolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable to record solo duty. 的本地化字符串。
        /// </summary>
        internal static string CheckboxEnableRecordSoloTooltip {
            get {
                return ResourceManager.GetString("CheckboxEnableRecordSoloTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to CSV 的本地化字符串。
        /// </summary>
        internal static string DataExport {
            get {
                return ResourceManager.GetString("DataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import from CSV 的本地化字符串。
        /// </summary>
        internal static string DataImport {
            get {
                return ResourceManager.GetString("DataImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to import. 的本地化字符串。
        /// </summary>
        internal static string DataImportFail {
            get {
                return ResourceManager.GetString("DataImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imported successfully. 的本地化字符串。
        /// </summary>
        internal static string DataImportSuccess {
            get {
                return ResourceManager.GetString("DataImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteHistoryEntry {
            get {
                return ResourceManager.GetString("DeleteHistoryEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold CTRL to Delete. 的本地化字符串。
        /// </summary>
        internal static string DeleteHistoryEntryCtrl {
            get {
                return ResourceManager.GetString("DeleteHistoryEntryCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This action is irreversible. 的本地化字符串。
        /// </summary>
        internal static string DeleteHistoryEntryWarning {
            get {
                return ResourceManager.GetString("DeleteHistoryEntryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confim Ignore 的本地化字符串。
        /// </summary>
        internal static string DoubleConfirmIgnore {
            get {
                return ResourceManager.GetString("DoubleConfirmIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration 的本地化字符串。
        /// </summary>
        internal static string DurationOfEntry {
            get {
                return ResourceManager.GetString("DurationOfEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Party Members 的本地化字符串。
        /// </summary>
        internal static string EntryParty {
            get {
                return ResourceManager.GetString("EntryParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string EntryTimeFromTo {
            get {
                return ResourceManager.GetString("EntryTimeFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore 的本地化字符串。
        /// </summary>
        internal static string IgnoreCurrentEntry {
            get {
                return ResourceManager.GetString("IgnoreCurrentEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed? 的本地化字符串。
        /// </summary>
        internal static string IsEntryCompleted {
            get {
                return ResourceManager.GetString("IsEntryCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Active Log. Display Last Entry Instead. 的本地化字符串。
        /// </summary>
        internal static string NotActiveButHaveHistory {
            get {
                return ResourceManager.GetString("NotActiveButHaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No record yet. 的本地化字符串。
        /// </summary>
        internal static string NotAnyRecord {
            get {
                return ResourceManager.GetString("NotAnyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Analyze 的本地化字符串。
        /// </summary>
        internal static string OpenAnalyzeWindow {
            get {
                return ResourceManager.GetString("OpenAnalyzeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job 的本地化字符串。
        /// </summary>
        internal static string PlayerJob {
            get {
                return ResourceManager.GetString("PlayerJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This plugin is in early development. Please report any bugs or suggestions to the developer. 的本地化字符串。
        /// </summary>
        internal static string PluginAboutInfo {
            get {
                return ResourceManager.GetString("PluginAboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can ping me at the Dalamud Discord server. Or open an issue at the GitHub repository. 的本地化字符串。
        /// </summary>
        internal static string PluginHowToFeedback {
            get {
                return ResourceManager.GetString("PluginHowToFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing... 的本地化字符串。
        /// </summary>
        internal static string QueryInProcess {
            get {
                return ResourceManager.GetString("QueryInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data available. 的本地化字符串。
        /// </summary>
        internal static string QueryNoResult {
            get {
                return ResourceManager.GetString("QueryNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frequency of Maps of each Roulette 的本地化字符串。
        /// </summary>
        internal static string QueryRouletteFrequency {
            get {
                return ResourceManager.GetString("QueryRouletteFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How much time for each roulette 的本地化字符串。
        /// </summary>
        internal static string QuerySpentTime {
            get {
                return ResourceManager.GetString("QuerySpentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top X pair of Roulette and Map 的本地化字符串。
        /// </summary>
        internal static string QueryTopX {
            get {
                return ResourceManager.GetString("QueryTopX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Join via 的本地化字符串。
        /// </summary>
        internal static string RouletteName {
            get {
                return ResourceManager.GetString("RouletteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        internal static string SettingTabAdvance {
            get {
                return ResourceManager.GetString("SettingTabAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string SettingTabData {
            get {
                return ResourceManager.GetString("SettingTabData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string SettingTabGeneral {
            get {
                return ResourceManager.GetString("SettingTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string TabNameAbout {
            get {
                return ResourceManager.GetString("TabNameAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        internal static string TabNameActive {
            get {
                return ResourceManager.GetString("TabNameActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History 的本地化字符串。
        /// </summary>
        internal static string TabNameHistory {
            get {
                return ResourceManager.GetString("TabNameHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        internal static string TabNameSetting {
            get {
                return ResourceManager.GetString("TabNameSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place 的本地化字符串。
        /// </summary>
        internal static string TerritoryName {
            get {
                return ResourceManager.GetString("TerritoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging Disabled. Read-Only Mode. 的本地化字符串。
        /// </summary>
        internal static string WarningWhenDisableLogging {
            get {
                return ResourceManager.GetString("WarningWhenDisableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently Logging 的本地化字符串。
        /// </summary>
        internal static string WhenLogging {
            get {
                return ResourceManager.GetString("WhenLogging", resourceCulture);
            }
        }
    }
}
