//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContactsTracker.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a suggestion for a new query, please let me know..
        /// </summary>
        internal static string AnalyzeFeedback {
            get {
                return ResourceManager.GetString("AnalyzeFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord: @lamitt.
        /// </summary>
        internal static string AuthorDiscord {
            get {
                return ResourceManager.GetString("AuthorDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Delete at Data Tab.
        /// </summary>
        internal static string ButtonDeleteAll {
            get {
                return ResourceManager.GetString("ButtonDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete ALL Active Entries.
        /// </summary>
        internal static string ButtonDeleteAllAction {
            get {
                return ResourceManager.GetString("ButtonDeleteAllAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the button to delete all active entries at Data Tab..
        /// </summary>
        internal static string ButtonDeleteAllTooltip {
            get {
                return ResourceManager.GetString("ButtonDeleteAllTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete ALL? This action is irreversible..
        /// </summary>
        internal static string ButtonDeleteAllWarning {
            get {
                return ResourceManager.GetString("ButtonDeleteAllWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string ButtonQuery {
            get {
                return ResourceManager.GetString("ButtonQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ButtonSelectNo {
            get {
                return ResourceManager.GetString("ButtonSelectNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ButtonSelectYes {
            get {
                return ResourceManager.GetString("ButtonSelectYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelIgnore {
            get {
                return ResourceManager.GetString("CancelIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Incomplete Entry.
        /// </summary>
        internal static string CheckboxEnableKeepEntry {
            get {
                return ResourceManager.GetString("CheckboxEnableKeepEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep record regardless of completion..
        /// </summary>
        internal static string CheckboxEnableKeepEntryTooltip {
            get {
                return ResourceManager.GetString("CheckboxEnableKeepEntryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Logging.
        /// </summary>
        internal static string CheckboxEnableLogging {
            get {
                return ResourceManager.GetString("CheckboxEnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to start recording data..
        /// </summary>
        internal static string CheckboxEnableLoggingTooltip {
            get {
                return ResourceManager.GetString("CheckboxEnableLoggingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Log Party.
        /// </summary>
        internal static string CheckboxEnableLogParty {
            get {
                return ResourceManager.GetString("CheckboxEnableLogParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Party Class.
        /// </summary>
        internal static string CheckboxEnableLogPartyClass {
            get {
                return ResourceManager.GetString("CheckboxEnableLogPartyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also record their class..
        /// </summary>
        internal static string CheckboxEnableLogPartyClassTooltip {
            get {
                return ResourceManager.GetString("CheckboxEnableLogPartyClassTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to log party members on completion..
        /// </summary>
        internal static string CheckboxEnableLogPartyTooltip {
            get {
                return ResourceManager.GetString("CheckboxEnableLogPartyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Record Duty Roulette.
        /// </summary>
        internal static string CheckboxEnableRecordRoulette {
            get {
                return ResourceManager.GetString("CheckboxEnableRecordRoulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to only record duty joined by roulette..
        /// </summary>
        internal static string CheckboxEnableRecordRouletteTooltip {
            get {
                return ResourceManager.GetString("CheckboxEnableRecordRouletteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Solo.
        /// </summary>
        internal static string CheckboxEnableRecordSolo {
            get {
                return ResourceManager.GetString("CheckboxEnableRecordSolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to record solo duty..
        /// </summary>
        internal static string CheckboxEnableRecordSoloTooltip {
            get {
                return ResourceManager.GetString("CheckboxEnableRecordSoloTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        internal static string DataExport {
            get {
                return ResourceManager.GetString("DataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from CSV.
        /// </summary>
        internal static string DataImport {
            get {
                return ResourceManager.GetString("DataImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import..
        /// </summary>
        internal static string DataImportFail {
            get {
                return ResourceManager.GetString("DataImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported successfully..
        /// </summary>
        internal static string DataImportSuccess {
            get {
                return ResourceManager.GetString("DataImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteHistoryEntry {
            get {
                return ResourceManager.GetString("DeleteHistoryEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold CTRL to Delete..
        /// </summary>
        internal static string DeleteHistoryEntryCtrl {
            get {
                return ResourceManager.GetString("DeleteHistoryEntryCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is irreversible..
        /// </summary>
        internal static string DeleteHistoryEntryWarning {
            get {
                return ResourceManager.GetString("DeleteHistoryEntryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confim Ignore.
        /// </summary>
        internal static string DoubleConfirmIgnore {
            get {
                return ResourceManager.GetString("DoubleConfirmIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string DurationOfEntry {
            get {
                return ResourceManager.GetString("DurationOfEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Members.
        /// </summary>
        internal static string EntryParty {
            get {
                return ResourceManager.GetString("EntryParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string EntryTimeFromTo {
            get {
                return ResourceManager.GetString("EntryTimeFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string IgnoreCurrentEntry {
            get {
                return ResourceManager.GetString("IgnoreCurrentEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed?.
        /// </summary>
        internal static string IsEntryCompleted {
            get {
                return ResourceManager.GetString("IsEntryCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Active Log. Display Last Entry Instead..
        /// </summary>
        internal static string NotActiveButHaveHistory {
            get {
                return ResourceManager.GetString("NotActiveButHaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record yet..
        /// </summary>
        internal static string NotAnyRecord {
            get {
                return ResourceManager.GetString("NotAnyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Analyze.
        /// </summary>
        internal static string OpenAnalyzeWindow {
            get {
                return ResourceManager.GetString("OpenAnalyzeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        internal static string PlayerJob {
            get {
                return ResourceManager.GetString("PlayerJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin is in early development. Please report any bugs or suggestions to the developer..
        /// </summary>
        internal static string PluginAboutInfo {
            get {
                return ResourceManager.GetString("PluginAboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can ping me at the Dalamud Discord server. Or open an issue at the GitHub repository..
        /// </summary>
        internal static string PluginHowToFeedback {
            get {
                return ResourceManager.GetString("PluginHowToFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        internal static string QueryInProcess {
            get {
                return ResourceManager.GetString("QueryInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available..
        /// </summary>
        internal static string QueryNoResult {
            get {
                return ResourceManager.GetString("QueryNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency of Maps of each Roulette.
        /// </summary>
        internal static string QueryRouletteFrequency {
            get {
                return ResourceManager.GetString("QueryRouletteFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much time for each roulette.
        /// </summary>
        internal static string QuerySpentTime {
            get {
                return ResourceManager.GetString("QuerySpentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top X pair of Roulette and Map.
        /// </summary>
        internal static string QueryTopX {
            get {
                return ResourceManager.GetString("QueryTopX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join via.
        /// </summary>
        internal static string RouletteName {
            get {
                return ResourceManager.GetString("RouletteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string SettingTabAdvance {
            get {
                return ResourceManager.GetString("SettingTabAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string SettingTabData {
            get {
                return ResourceManager.GetString("SettingTabData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingTabGeneral {
            get {
                return ResourceManager.GetString("SettingTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string TabNameAbout {
            get {
                return ResourceManager.GetString("TabNameAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string TabNameActive {
            get {
                return ResourceManager.GetString("TabNameActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string TabNameHistory {
            get {
                return ResourceManager.GetString("TabNameHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string TabNameSetting {
            get {
                return ResourceManager.GetString("TabNameSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string TerritoryName {
            get {
                return ResourceManager.GetString("TerritoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Disabled. Read-Only Mode..
        /// </summary>
        internal static string WarningWhenDisableLogging {
            get {
                return ResourceManager.GetString("WarningWhenDisableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Logging.
        /// </summary>
        internal static string WhenLogging {
            get {
                return ResourceManager.GetString("WhenLogging", resourceCulture);
            }
        }
    }
}
