name: Build My Plugin

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build
        run: |
          dotnet build -c Release

      - name: Upload a Build Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ContactsTracker
          path: |
            ContactsTracker/bin/x64/Release/*

      - name: Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ContactsTracker.zip
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
